### ISSUE TITLE
debian packages for 1.1.8 python3-rospkg-modules has incorrect dependency on python3-catkin-pkg

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/rospkg#168] opened 2019-04-16 07:30 UTC
I was trying to install python3-rospkg-modules side by side with a kinetic installation and found that I couldn't because it was depending on python3-catkin-pkg
```
$ sudo apt-get install python3-rospkg-modules
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-rospkg-modules : Depends: python3-catkin-pkg but it is not going to be installed
```

Looking deeper it's coming from shadow fixed:
```
$ apt-cache policy python3-rospkg-modules
python3-rospkg-modules:
  Installed: (none)
  Candidate: 1.1.8-1
  Version table:
     1.1.8-1 500
        500 http://packages.ros.org/ros-shadow-fixed/ubuntu xenial/main amd64 Packages
```
And from: http://packages.ros.org/ros-shadow-fixed/ubuntu/dists/xenial/main/binary-amd64/Packages it does have that dependency:
```
Package: python3-rospkg-modules
Priority: optional
Section: python
Installed-Size: 130
Maintainer: Ken Conley <kwc@willowgarage.com>
Architecture: all
Version: 1.1.8-1
Replaces: python3-rospkg (<< 1.1.0)
Depends: python3-catkin-pkg, python3-yaml, python3:any (>= 3.4~), lsb-release
Conflicts: python3-rospkg (<< 1.1.0)
Filename: pool/main/p/python3-rospkg-modules/python3-rospkg-modules_1.1.8-1_all.deb
SHA512: 7cee00650e45bd0b92774440833b15ae5b735bec79d1dad74d3b6ab651a50bcacd2d337c51d707926ef1f78e8d7f898bb59ea0a13fcbb741abfa51087beea05f
Size: 23744
SHA256: fd69d97af0b039e8f595b15c38f59a8b0f7171a399e2d95183e3b0e6c851272f
SHA1: ecb8555b0606f1bc52a23fda35a0589853005371
MD5sum: 00547ca3268a2e5f5fddd6829825b73b
Description: ROS package library
         Library for retrieving information about ROS packages and stacks.
Homepage: http://wiki.ros.org/rospkg
```

This appears to be a regression so far only in shadow-fixed. http://packages.ros.org/ros/ubuntu/dists/xenial/main/binary-amd64/Packages

```
Package: python3-rospkg-modules
Version: 1.1.7-1
Architecture: all
Maintainer: Ken Conley <kwc@willowgarage.com>
Installed-Size: 130
Depends: python3-yaml, python3:any (>= 3.2~), lsb-release
Conflicts: python3-rospkg (<< 1.1.0)
Replaces: python3-rospkg (<< 1.1.0)
Priority: optional
Section: python
Filename: pool/main/p/python3-rospkg-modules/python3-rospkg-modules_1.1.7-1_all.deb
Size: 23484
SHA256: aef0f2da3d94ce849fc6f70be3cacb5361a0d168ce449ea61fa5411a22728d03
SHA1: 32f597b32eea14fa51ea182e14425d538fd2bc1f
MD5sum: c510406605b8423b332e76c45b45e5da
Description: ROS package library
         Library for retrieving information about ROS packages and stacks.
```

It doesn't appear that there's anything changed in the stdeb.cfg recently: https://github.com/ros-infrastructure/rospkg/commits/master/stdeb.cfg

@dirk-thomas was this run on a machine from which you've made releases before?

Also it appears that the python2 version also has the invalid dependency also in shadow fixed.
```
Package: python-rospkg-modules
Priority: optional
Section: python
Installed-Size: 130
Maintainer: Ken Conley <kwc@willowgarage.com>
Architecture: all
Version: 1.1.8-1
Replaces: python-rospkg (<< 1.1.0)
Depends: python-catkin-pkg, python-yaml, python:any (<< 2.8), python:any (>= 2.7.5-5~), lsb-release
Conflicts: python-rospkg (<< 1.1.0)
Filename: pool/main/p/python-rospkg-modules/python-rospkg-modules_1.1.8-1_all.deb
SHA512: a4074377fad4ac1cac1009a29c1b4ffdb1d7364ae04f30bb85a716f80d8ab61b03189cefabef59b5afca2ae72fdac2fd54da6f232f8e9b52cb0930e1f4490f6f
Size: 23684
SHA256: 010ab3c4c52e92b9853161bde2c8141520b886ad371ca0a275b8e2e5ce635d45
SHA1: 8d18c8dc5c45179a8ae75aff1c55798984a05596
MD5sum: 4493868887f9aaaaecd983d266dfe72b
Description: ROS package library
         Library for retrieving information about ROS packages and stacks.
Homepage: http://wiki.ros.org/rospkg
```

**Comment by tfoote** [comment] 2019-04-16 07:32
@nuclearsandwich FYI and do you know why the stanzas are different between shadow-fixed and public? The shadow-fixed ones seem to have more entries overall.

**Comment by nuclearsandwich** [comment] 2019-04-16 12:04
cc @mxgrey as we hit this yesterday and I was coming to report the same thing.

>  FYI and do you know why the stanzas are different between shadow-fixed and public? The shadow-fixed ones seem to have more entries overall.

From this [internal discussion](https://osrf.slack.com/archives/C5UEHBHD2/p1555012569003900?thread_ts=1555001674.001900&cid=C5UEHBHD2) the reason they're in the shadow fixed and ROS 2 testing repositories without being in the main ones is that uploads have occurred for testing but not yet for main on either buildfarm.

As to why this is happening... I am able to reproduce creating a deb with the catkin-pkg dependency in my local release environment which hasn't been updated in quite some time. However I get the catkin-pkg dependency when I create debs for both 1.1.7 and 1.1.8.

This is the control file generated by stdeb. I think the `${python:Depends}` is introspecting the setuptools declared dependencies, which includes catkin-pkg, and resolving them to Debian packages.

```
❯ cat deb_dist/python-rospkg-modules-1.1.7/debian/control
Source: python-rospkg-modules
Maintainer: Ken Conley <kwc@willowgarage.com>
Section: python
Priority: optional
Build-Depends: python-setuptools (>= 0.6b3), python-all (>= 2.6.6-3), debhelper (>= 7.4.3)
Standards-Version: 3.9.1
X-Python3-Version: >= 3.2



Package: python-rospkg-modules
Architecture: all
Depends: ${misc:Depends}, ${python:Depends}, python-yaml, lsb-release
Conflicts: python-rospkg (<< 1.1.0)
Replaces: python-rospkg (<< 1.1.0)
Description: ROS package library
         Library for retrieving information about ROS packages and stacks.
 .
```

**Comment by dirk-thomas** [comment] 2019-04-16 16:49
> was this run on a machine from which you've made releases before?

Same machine, the usual setup (`setuptools` is being updated over time). A local rebuild of the package does have these dependencies (which it shouldn't).

> do you know why the stanzas are different between shadow-fixed and public?

There was a race condition in the `import_upstream` job for that specific package:
* http://build.ros.org/job/import_upstream/333/ (failed) and http://build.ros.org/job/import_upstream/333/
* http://build.ros2.org/job/import_upstream/140/ (didn't fail but might still have a problem?) and http://build.ros2.org/job/import_upstream/141/

**Closed** 2019-04-16 20:07 UTC
Labels: bug
